name: Build and Push Docker Images

on:
  push:
    branches: [ main ]

env: 
  GO_MAJOR_VERSION: 1
  GO_MAJOR_MINOR_VERSION: 1.22
  GO_VERSION: 1.22.3
  
  BASE_IMAGE_OS_VERSION: bullseye
  BASE_IMAGE_VERSION: 1.22.3-bullseye
  
  IMAGE_NAME: go
  IMAGE_MAJOR_VERSION: 1
  IMAGE_MAJOR_MINOR_VERSION: 1.0
  IMAGE_VERSION: 1.0.0

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version_prefix: [
          "latest",
          # "${{ env.IMAGE_MAJOR_VERSION }}",
          # "${{ env.IMAGE_MAJOR_MINOR_VERSION }}",
          # "${{ env.IMAGE_VERSION }}"
        ]
        suffix_version: [
          "",
          # "-${{ env.GO_MAJOR_VERSION }}",
          # "-${{ env.GO_MAJOR_VERSION }}-${{ env.BASE_IMAGE_OS_VERSION }}",
          # "-${{ env.GO_MAJOR_MINOR_VERSION }}",
          # "-${{ env.GO_MAJOR_MINOR_VERSION }}-${{ env.BASE_IMAGE_OS_VERSION }}",
          # "-${{ env.GO_VERSION }}",
          # "-${{ env.BASE_IMAGE_VERSION }}",
        ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ matrix.version_prefix }}${{ matrix.suffix_version }}
          build-args: |
            BASE_IMAGE_VERSION=${{ env.BASE_IMAGE_VERSION }}
