name: CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'

env: 
  IMAGE_NAME: go
  GO_MAJOR_VERSION: 1
  GO_MAJOR_MINOR_VERSION: 1.22
  GO_VERSION: 1.22.3
  BASE_IMAGE_OS_VERSION: bullseye
  BASE_IMAGE_TAG: 1.22.3-bullseye
  REGISTRY: ghcr.io

jobs:
  build_and_push:
    name: Build and Push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: docker_meta
        name: Docker meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/ThomasSousa96/test-foo
          tags: |
            type=schedule
            type=semver,pattern={{version}}
            type=semver,pattern={{version}}-${{ env.BASE_IMAGE_TAG }}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}.{{minor}}-${{ env.GO_MAJOR_MINOR_VERSION }}
            type=semver,pattern={{major}}.{{minor}}-${{ env.GO_VERSION }}
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}-${{ env.GO_MAJOR_MINOR_VERSION }}
            type=semver,pattern={{major}}-${{ env.GO_VERSION }}
            type=semver,pattern={{major}}-${{ env.BASE_IMAGE_TAG }}
            type=ref,event=pr
            type=sha
          labels: |
            org.opencontainers.image.description=Foooooooo

      - name: Log in to the Container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Login to Docker Hub
      #   if: github.event_name != 'pull_request'
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          annotations: ${{ steps.docker_meta.outputs.annotations }}
          build-args: |
            BASE_IMAGE_TAG=${{ env.BASE_IMAGE_TAG }}

      # - name: Update repo description
      #   uses: peter-evans/dockerhub-description@v4.0.0 # v4.0.0
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      #     repository: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}