name: CI

on:
  push:
    branches: [ main ]
    tags:
      - v*
  pull_request:
    branches:
      - main

env: 
  BASE_IMAGE_MAJOR_VERSION: 1
  BASE_IMAGE_MINOR_VERSION: 22
  BASE_IMAGE_TAG: 1.22.3-bullseye
  BASE_IMAGE_NAME_PREFIX: go
  IMAGE_NAME: ${{ github.repository	}}
  PUSH_TO_DOCKER_HUB: ${{ github.ref_type == 'tag' }}
  PUSH_TO_GHCR: ${{ github.ref_type == 'tag' }}
  GHCR_ADDRESS: ghcr.io

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  add-pr-labels:
    name: Add PR labels
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add PR labels
        uses: actions/labeler@v5

  dependency-review:
    name: Dependency review
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dependency review
        uses: actions/dependency-review-action@v4
        with:
          comment-summary-in-pr: true
          fail-on-scopes: runtime,development,unknown
          license-check: true
          vulnerability-check: true

  sonnar:
    name: Sonnar scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build-and-push:
    name: Build and push
    needs:
      - dependency-review
      - sonnar
    runs-on: ubuntu-latest
    if: ${{ !cancelled() && !failure() }}
    permissions:
      contents: read
      packages: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Define env.IMAGE_NAMES
        run: |
          IMAGE_NAMES=$IMAGE_NAME
          if [[ "$PUSH_TO_GHCR" == "true" ]]; then
            GHCR_IMAGE_NAME="$GHCR_ADDRESS/$IMAGE_NAME"
            IMAGE_NAMES="$IMAGE_NAMES,$GHCR_IMAGE_NAME"
          fi
          echo "IMAGE_NAMES=$IMAGE_NAMES" >> $GITHUB_ENV

      - id: docker_meta
        name: Extract docker metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAMES }}
          tags: |
            type=semver,pattern={{major}}-${{ env.BASE_IMAGE_NAME_PREFIX }}-${{ env.BASE_IMAGE_MAJOR_VERSION }}
            type=semver,pattern={{major}}-${{ env.BASE_IMAGE_NAME_PREFIX }}-${{ env.BASE_IMAGE_MAJOR_VERSION }}.${{ env.BASE_IMAGE_MINOR_VERSION }}
            type=semver,pattern={{major}}.{{minor}}-${{ env.BASE_IMAGE_NAME_PREFIX }}-${{ env.BASE_IMAGE_MAJOR_VERSION }}.${{ env.BASE_IMAGE_MINOR_VERSION }}
            type=semver,pattern={{version}}-${{ env.BASE_IMAGE_NAME_PREFIX }}-${{ env.BASE_IMAGE_TAG }}
            type=ref,event=branch
            type=ref,event=pr
            type=sha

      - name: Login to the Docker Hub
        if: ${{ env.PUSH_TO_DOCKER_HUB }}
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to the Github Container Registry (GHCR)
        if: ${{ env.PUSH_TO_GHCR }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GHCR_ADDRESS }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ env.PUSH_TO_DOCKER_HUB || env.PUSH_TO_GHCR }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          annotations: ${{ steps.docker_meta.outputs.annotations }}
          build-args: |
            BASE_IMAGE_TAG=${{ env.BASE_IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          sbom: true
          provenance: mode=max

      - name: Generate build summary
        id: generate-build-summary
        env:
          BUILD_SUMMARY: |
            ### [Docker image](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) :rocket:
            
            <details open>
              <summary>Tags</summary>
            
              ```
              ${{ steps.docker_meta.outputs.tags }}
              ```
            </details>

            <details>
              <summary>Labels</summary>
            
              ```
              ${{ steps.docker_meta.outputs.labels }}
              ```
            </details>
            
            <details>
              <summary>Annotations</summary>
            
              ```
              ${{ steps.docker_meta.outputs.annotations }}
              ```
            </details>

        run: |
          BUILD_SUMMARY_PATH="${{ runner.temp }}/build-summary.md"
          echo "BUILD_SUMMARY_PATH=$BUILD_SUMMARY_PATH" >> $GITHUB_ENV
          echo "$BUILD_SUMMARY" > $BUILD_SUMMARY_PATH
          echo "$BUILD_SUMMARY" >> $GITHUB_STEP_SUMMARY

      - name: Comment on pull request
        if: ${{ github.event_name == 'pull_request' }}
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue comment ${{ github.event.number }} --body-file $BUILD_SUMMARY_PATH

    outputs:
      tags: ${{ steps.docker_meta.outputs.tags }}
      labels: ${{ steps.docker_meta.outputs.labels }}
      annotations: ${{ steps.docker_meta.outputs.annotations }}

  create-release:
    name: Create release
    needs: build-and-push
    runs-on: ubuntu-latest
    if: ${{ success() }}
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Test
        run: |
          echo "${{ github.ref_type }}"

      - name: Create Github release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_NOTES: |
            # Version ${{ github.ref_name }}
            
            ## Changelog

            * ordgordighrdg
            * çeflseropfespof
            * epfpekpfespo
            * rlfgrgprepogr

            ## Docker image :rocket:
            
            <details open>
              <summary>Tags</summary>
            
              ```
              ${{ needs.build-and-push.outputs.tags }}
              ```
            </details>

            <details>
              <summary>Labels</summary>
            
              ```
              ${{ needs.build-and-push.outputs.labels }}
              ```
            </details>
            
            <details>
              <summary>Annotations</summary>
            
              ```
              ${{ needs.build-and-push.outputs.annotations }}
              ```
            </details>


        run: |
          gh release create ${{ github.ref_name }} \
            --title "${{ github.ref_name }}" \
            --notes "$NOTES" \
            --latest \
            --verify-tag \
            --generate-notes \
            --target main \
            --discussion-category "announcements"
          echo "$RELEASE_NOTES" >> $GITHUB_STEP_SUMMARY
  
  # sbom-upload:
  #   name: SBOM upload
  #   needs: build-and-push
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: write
  #   steps:
  #     - name: SBOM upload
  #       uses: advanced-security/spdx-dependency-submission-action@v0.0.1
  #       with:
  #         filePath: "_manifest/spdx_2.2/"
