name: CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags:
      - v*
  pull_request:
    branches:
      - main

env: 
  BASE_IMAGE_MAJOR_VERSION: 1
  BASE_IMAGE_MINOR_VERSION: 22
  BASE_IMAGE_TAG: 1.22.3-bullseye
  BASE_IMAGE_NAME_PREFIX: go
  IMAGE_NAME: ${{ github.repository	}}
  PUSH_TO_DOCKER_HUB: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
  PUSH_TO_GHCR: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
  GHCR_ADDRESS: ghcr.io

jobs:
  review:
    name: Review
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add labels
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/labeler@v5

      - name: Dependency review
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/dependency-review-action@v4
        with:
          comment-summary-in-pr: true
          fail-on-scopes: runtime,development,unknown
          license-check: true
          vulnerability-check: true

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build_and_push:
    name: Build and Push
    needs: review
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Define env.IMAGE_NAMES
        run: |
          IMAGE_NAMES=$IMAGE_NAME
          if [[ "$PUSH_TO_GHCR" == "true" ]]; then
            GHCR_IMAGE_NAME="$GHCR_ADDRESS/$IMAGE_NAME"
            IMAGE_NAMES="$IMAGE_NAMES,$GHCR_IMAGE_NAME"
          fi
          echo "IMAGE_NAMES=$IMAGE_NAMES" >> $GITHUB_ENV

      - id: docker_meta
        name: Extract docker metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAMES }}
          tags: |
            type=semver,pattern={{major}}-${{ env.BASE_IMAGE_NAME_PREFIX }}-${{ env.BASE_IMAGE_MAJOR_VERSION }}
            type=semver,pattern={{major}}-${{ env.BASE_IMAGE_NAME_PREFIX }}-${{ env.BASE_IMAGE_MAJOR_VERSION }}.${{ env.BASE_IMAGE_MINOR_VERSION }}
            type=semver,pattern={{major}}.{{minor}}-${{ env.BASE_IMAGE_NAME_PREFIX }}-${{ env.BASE_IMAGE_MAJOR_VERSION }}.${{ env.BASE_IMAGE_MINOR_VERSION }}
            type=semver,pattern={{version}}-${{ env.BASE_IMAGE_NAME_PREFIX }}-${{ env.BASE_IMAGE_TAG }}
            type=ref,event=pr

      - name: Login to the Docker Hub
        if: ${{ env.PUSH_TO_DOCKER_HUB }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to the Github Container Registry (GHCR)
        if: ${{ env.PUSH_TO_GHCR }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GHCR_ADDRESS }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ env.PUSH_TO_DOCKER_HUB || env.PUSH_TO_GHCR }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          annotations: ${{ steps.docker_meta.outputs.annotations }}
          build-args: |
            BASE_IMAGE_TAG=${{ env.BASE_IMAGE_TAG }}
