name: Delete cache

on:
  workflow_dispatch:
    inputs:
      oldest-cache-entries:
        description: Oldest cache entries
        required: true
        default: 1
        type: number

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  delete-cache:
    name: Delete Github cache
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get cache keys
        run: |
          CACHE_KEYS=$(gh cache list --order asc --limit ${{ inputs.oldest-cache-entries }} --json key --jq '.[].key')
          echo $CACHE_KEYS
          echo "cacheKeys=$CACHE_KEYS" >> $GITHUB_ENV
      
      - name: Delete cache
        run: |
          set +e
          for CACHE_KEY in $CACHE_KEYS
          do
            echo "Deleting cache by key: '$CACHE_KEY'
            gh cache delete $CACHE_KEY
          done
    