name: Delete cache

on:
  workflow_dispatch:
    inputs:
      oldest-cache-entries:
        description: Oldest cache entries
        required: true
        default: 1
        type: number

jobs:
  delete-cache:
    name: Delete cache
    runs-on: ubuntu-latest
    permissions:
      actions: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v4

      - name: Delete Github cache
        run: |
          CACHE_KEYS=$(gh cache list --order asc --limit ${{ inputs.oldest-cache-entries }} --json key --jq '.[].key')
          set +e
          for CACHE_KEY in $CACHE_KEYS
          do
            echo "Deleting $CACHE_KEY..."
            gh cache delete $CACHE_KEY
          done
