name: Labels

on:
  pull_request:

jobs:
  add-labels:
    name: Add labels
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      
      - name: Add labels
        uses: actions/labeler@v5
